# Generated by Django 4.0.3 on 2024-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotipie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
